# k8s-config-secret-lab/deployment-service.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app-deployment
  namespace: default
  labels:
    app: my-k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-k8s-app
  template:
    metadata:
      labels:
        app: my-k8s-app
    spec:
      containers:
      - name: my-k8s-app-container
        image: your_docker_repo/my-k8s-app:1.0 # <<-- IMPORTANT: UPDATE THIS TO YOUR IMAGE
        ports:
        - containerPort: 5000
        env:
        - name: APP_TITLE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_TITLE
        - name: WELCOME_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: WELCOME_MESSAGE
        - name: APP_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_LOG_LEVEL
        - name: NEW_CONFIG_VALUE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NEW_CONFIG_VALUE
        volumeMounts:
        - name: app-secret-volume
          mountPath: "/etc/app-secrets"
          readOnly: true
      volumes:
      - name: app-secret-volume
        secret:
          secretName: app-secrets
          defaultMode: 0400
---
apiVersion: v1
kind: Service
metadata:
  name: my-k8s-app-service
  namespace: default
spec:
  selector:
    app: my-k8s-app
  ports:
  - protocol: TCP
    port: 80 # Service port
    targetPort: 5000 # Container port
    # nodePort: 30000-32767 # Optional: You can specify a nodePort here, or let K8s assign one
  type: NodePort # <<-- CHANGED FROM LoadBalancer TO NodePort
