# k8s-config-secret-lab/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default # Ensure this matches your deployment namespace
type: Opaque # Default type for arbitrary user-defined data
stringData: # Use stringData for plain text, K8s will base64 encode
  DB_USERNAME: "k8s_user"
  DB_PASSWORD: "Sup3rS3cr3tP@ss!"
  API_KEY: "abc-123-xyz-456-api-key-test"
