apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-test-daemonset
  labels:
    app: nginx-test
spec:
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx-test-container
        image: nginx:latest # Latest Nginx image
        ports:
        - containerPort: 80
          name: http-web
