apiVersion: v1
kind: Service
metadata:
  name: myapp-nodeport
  labels:
    app: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 80              # ClusterIP port
      targetPort: 80        # Pod/container port
      nodePort: 30083       # Optional: specify a NodePort (within range 30000–32767)
      protocol: TCP

