apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-app-deployment
  labels:
    app: my-first-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-first-app
  template:
    metadata:
      labels:
        app: my-first-app
    spec:
      containers:
      - name: my-first-app-container
        image: nginx:latest # This will pull the latest Nginx image
        ports:
        - containerPort: 80
