apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    name: saravana
spec:
  type: ClusterIP  # This is optional as ClusterIP is the default
  selector:
    app: myapp      # Must match the Deployment's Pod label
  ports:
    - port: 80              # Port exposed by the Service
      targetPort: 80        # Port on the container
      protocol: TCP
