apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
spec:
  capacity:
    storage: 5Gi                 # match size of the EBS volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce             # only one pod can mount it at a time
  persistentVolumeReclaimPolicy: Retain  # keep volume after PVC is deleted
  storageClassName: manual
  awsElasticBlockStore:
    volumeID: vol-0123456789abcdef0   # your actual EBS volume ID
    fsType: ext4
